name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore E:\PersonalProjects\EmailSenderApp
        
      - name: Build
        run: dotnet build E:\PersonalProjects\EmailSenderApp --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish E:\PersonalProjects\EmailSenderApp --configuration Release --no-build
